### ISSUE TITLE
Example file didn't work well

### ISSUE THREAD

**Issue by d1015** [hammerlab/cytokit#43]
When I tried to run the example, it reported the following errors.

2022-09-07 21:04:53,032:INFO:91:root: Execution arguments and environment saved to "/tmp/cytokit-example/cellular-marker/20181116-d40-r1-20x-5by5/output/v00/processor/execution/202209072104.json"
2022-09-07 21:05:00,776:INFO:91:cytokit.exec.pipeline: Starting Pre-processing pipeline for 1 tasks (1 workers)
2022-09-07 21:05:00,794:INFO:107:cytokit.data: Downloading url "https://storage.googleapis.com/microscope-image-quality/static/model/model.ckpt-1000042.index" to local path "/lab/data/.cytokit/cache/best_focus/model/model.ckpt-1000042.index"
2022-09-07 21:05:02,492:INFO:107:cytokit.exec.pipeline: Loaded tile 1 for region 1 [shape = (1, 7, 4, 1440, 1920)]
2022-09-07 21:05:05,007:INFO:107:cytokit.data: Downloading url "https://storage.googleapis.com/microscope-image-quality/static/model/model.ckpt-1000042.meta" to local path "/lab/data/.cytokit/cache/best_focus/model/model.ckpt-1000042.meta"
2022-09-07 21:05:06,764:INFO:107:cytokit.data: Downloading url "https://storage.googleapis.com/microscope-image-quality/static/model/model.ckpt-1000042.data-00000-of-00001" to local path "/lab/data/.cytokit/cache/best_focus/model/model.ckpt-1000042.data-00000-of-00001"
Using TensorFlow backend.
distributed.worker - WARNING -  Compute Failed
Function:  run_preprocess_task
args:      ({'tile_prefetch_capacity': 1, 'op_flags': <cytokit.exec.pipeline.OpFlags object at 0x7f334cab47b8>, 'output_dir': '/tmp/cytokit-example/cellular-marker/20181116-d40-r1-20x-5by5/output/v00', 'gpu': 0, 'tile_indexes': array([0]), 'region_indexes': array([0]), 'data_dir': '/tmp/cytokit-example/cellular-marker/20181116-d40-r1-20x-5by5/raw'})
kwargs:    {}
Exception: OSError('Unable to open file (file signature not found)',)

Traceback (most recent call last):
  File "/usr/local/bin/cytokit", line 32, in <module>
    main()
  File "/usr/local/bin/cytokit", line 28, in main
    fire.Fire(Cytokit)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/lab/repos/cytokit/python/pipeline/cytokit/cli/__init__.py", line 167, in run_all
    fn(**{**config[op], **params})
  File "/lab/repos/cytokit/python/pipeline/cytokit/cli/processor.py", line 131, in run
    pipeline.run(pl_config, logging_init_fn=self._logging_init_fn)
  File "/lab/repos/cytokit/python/pipeline/cytokit/exec/pipeline.py", line 458, in run
    run_tasks(pl_conf, 'Pre-processing', run_preprocess_task, logging_init_fn)
  File "/lab/repos/cytokit/python/pipeline/cytokit/exec/pipeline.py", line 421, in run_tasks
    res = [r.result() for r in res]
  File "/lab/repos/cytokit/python/pipeline/cytokit/exec/pipeline.py", line 421, in <listcomp>
    res = [r.result() for r in res]
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/distributed/client.py", line 227, in result
    six.reraise(*result)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/lab/repos/cytokit/python/pipeline/cytokit/exec/pipeline.py", line 441, in run_preprocess_task
    return run_task(task, ops, preprocess_tile)
  File "/lab/repos/cytokit/python/pipeline/cytokit/exec/pipeline.py", line 355, in run_task
    with ops:
  File "/lab/repos/cytokit/python/pipeline/cytokit/ops/op.py", line 200, in __enter__
    v.__enter__()
  File "/lab/repos/cytokit/python/pipeline/cytokit/ops/op.py", line 152, in __enter__
    self.initialize()
  File "/lab/repos/cytokit/python/pipeline/cytokit/ops/cytometry.py", line 136, in initialize
    self.cytometer.initialize()
  File "/lab/repos/cytokit/python/pipeline/cytokit/cytometry/cytometer.py", line 610, in initialize
    self.model.load_weights(self.weights_path or self._get_weights_path())
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/keras/engine/network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
Traceback (most recent call last):
  File "/usr/local/bin/cytokit", line 32, in <module>
    main()
  File "/usr/local/bin/cytokit", line 28, in main
    fire.Fire(Cytokit)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/lab/repos/cytokit/python/pipeline/cytokit/cli/__init__.py", line 167, in run_all
    fn(**{**config[op], **params})
  File "/lab/repos/cytokit/python/pipeline/cytokit/cli/operator.py", line 135, in extract
    z_slice_fn = _get_z_slice_fn(z, self.data_dir)
  File "/lab/repos/cytokit/python/pipeline/cytokit/cli/operator.py", line 78, in _get_z_slice_fn
    map = function_data.get_best_focus_coord_map(data_dir)
  File "/lab/repos/cytokit/python/pipeline/cytokit/function/data.py", line 45, in get_best_focus_coord_map
    return get_best_focus_data(output_dir).set_index(['region_index', 'tile_x', 'tile_y'])['best_z'].to_dict()
  File "/lab/repos/cytokit/python/pipeline/cytokit/function/data.py", line 31, in get_best_focus_data
    processor_data, path = get_processor_data(output_dir, return_path=True)
  File "/lab/repos/cytokit/python/pipeline/cytokit/function/data.py", line 19, in get_processor_data
    proc_data = exec.read_processor_data(path)
  File "/lab/repos/cytokit/python/pipeline/cytokit/exec/__init__.py", line 34, in read_processor_data
    with open(path, 'r') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/cytokit-example/cellular-marker/20181116-d40-r1-20x-5by5/output/v00/processor/data.json'
2022-09-07 21:07:19,050:INFO:189:root: Running cytometry statistics aggregation
2022-09-07 21:07:19,051:WARNING:189:cytokit.cytometry.data: Expected cytometry data file at "/tmp/cytokit-example/cellular-marker/20181116-d40-r1-20x-5by5/output/v00/cytometry/statistics/R001_X001_Y001.csv" does not exist.  It will be ignored but this may be worth investigating
Traceback (most recent call last):
  File "/usr/local/bin/cytokit", line 32, in <module>
    main()
  File "/usr/local/bin/cytokit", line 28, in main
    fire.Fire(Cytokit)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/lab/repos/cytokit/python/pipeline/cytokit/cli/__init__.py", line 167, in run_all
    fn(**{**config[op], **params})
  File "/lab/repos/cytokit/python/pipeline/cytokit/cli/analysis.py", line 28, in aggregate_cytometry_statistics
    self.data_dir, self.config, mode=mode, export_csv=export_csv, export_fcs=export_fcs, variant=variant)
  File "/lab/repos/cytokit/python/pipeline/cytokit/function/core.py", line 19, in aggregate_cytometry_statistics
    res = function_data.get_cytometry_data(output_dir, config, mode=mode)
  File "/lab/repos/cytokit/python/pipeline/cytokit/function/data.py", line 59, in get_cytometry_data
    cyto_data = cytometry_data.aggregate(config, output_dir)
  File "/lab/repos/cytokit/python/pipeline/cytokit/cytometry/data.py", line 32, in aggregate
    df = pd.concat(df)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/pandas/core/reshape/concat.py", line 212, in concat
    copy=copy)
  File "/opt/conda/envs/cytokit/lib/python3.5/site-packages/pandas/core/reshape/concat.py", line 245, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

Do you have any ideas to figure out the issue?
Thanks a lot.

**Comment by eric-czech** [comment]
It's hard to say much without knowing what configuration you used and how you invoked the script.  Do you still have those things?
